package Exception;

public class Prog2 {

	public static void main(String[] args) {
	//	System.out.println(10/0);
		//throw new ArithmeticException();//by using throw we are throwing exception
		//so here we are taking responsibility of throwing exception
		//but after this program will not going to execute
		//Thread.sleep(1000);
		try
		{
		Thread.sleep(2000);
		}
		catch(Exception e){}
		}
	
	}


